// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracap_App_API.Data;

#nullable disable

namespace Oracap_App_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Oracap_App_API.Model.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HexaColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Oracap_App_API.Model.PrayTypeModel", b =>
                {
                    b.Property<int>("PrayTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrayTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrayTypeId");

                    b.ToTable("PrayTypes");
                });

            modelBuilder.Entity("Oracap_App_API.Model.PrayerModel", b =>
                {
                    b.Property<int>("PrayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrayerId"));

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PrayTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ViewTypeId")
                        .HasColumnType("int");

                    b.HasKey("PrayerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrayTypeId");

                    b.HasIndex("ViewTypeId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("Oracap_App_API.Model.ViewTypeModel", b =>
                {
                    b.Property<int>("ViewTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ViewTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ViewTypeId");

                    b.ToTable("ViewTypes");
                });

            modelBuilder.Entity("Oracap_App_API.Model.PrayerModel", b =>
                {
                    b.HasOne("Oracap_App_API.Model.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Oracap_App_API.Model.PrayTypeModel", "PrayType")
                        .WithMany()
                        .HasForeignKey("PrayTypeId");

                    b.HasOne("Oracap_App_API.Model.ViewTypeModel", "ViewType")
                        .WithMany()
                        .HasForeignKey("ViewTypeId");

                    b.Navigation("Category");

                    b.Navigation("PrayType");

                    b.Navigation("ViewType");
                });
#pragma warning restore 612, 618
        }
    }
}
